wireplumber.components = [
  {
    name     = bt-autoswitch.lua
    type     = script/lua
    provides = custom.bt-autoswitch
  }
]

wireplumber.profiles = {
  main = {
    custom.bt-autoswitch = optional
  }
}
