# tmpfiles.d for panicos-samba
# type path mode user group
d /run/samba                   0755 root root -
d /var/lib/samba               0755 root root -
d /var/cache/samba             0755 root root -
d /storage/.cache/services     0755 root root -
