#!/bin/sh
# Render /run/wpa_supplicant.conf from a user-editable file on the boot
# vfat. Lookup order, first hit wins:
#
#   1. wpa_supplicant.conf  — raw drop-in, used verbatim (power-user)
#   2. panicos-wifi.cfg     — key=value, rendered into wpa_supplicant.conf
#   3. neither              — exit 0, no output (skip wifi entirely)
#
# Source files live on /boot (ro from userland — read each boot, never
# stored on the overlay). Output is on tmpfs so a flash partition edit
# takes effect on next boot.
#
# Env-var overrides for testing: PANICOS_WIFI_BOOT_DIR, PANICOS_WIFI_OUT.

set -eu
# Requires bash, or busybox ash with ASH_BASH_COMPAT=y (the buildroot
# default — confirmed in our build configs). Without pipefail support
# the wpa_passphrase failure case would silently mask via the empty
# HASHED guard alone.
set -o pipefail

BOOT_DIR="${PANICOS_WIFI_BOOT_DIR:-/boot}"
OUT="${PANICOS_WIFI_OUT:-/run/wpa_supplicant.conf}"

RAW="$BOOT_DIR/wpa_supplicant.conf"
KV="$BOOT_DIR/panicos-wifi.cfg"

# Case 1: raw drop-in.
if [ -s "$RAW" ]; then
    mkdir -p "$(dirname "$OUT")"
    cp "$RAW" "$OUT"
    chmod 0600 "$OUT"
    echo ">>> panicos-wifi-config: using raw $RAW"
    exit 0
fi

# Case 2: key=value.
if [ -s "$KV" ]; then
    SSID=""; PSK=""; COUNTRY=""; HIDDEN="0"
    # Strip an inline comment (everything from the first ` #` onward) plus
    # leading/trailing whitespace from a parsed value. Without this, the
    # template's "COUNTRY=US      # ISO 3166..." comment would land verbatim
    # inside wpa_supplicant.conf and the country line would be invalid.
    # Note: this DOES strip the trailing chunk if a PSK or SSID legitimately
    # contains ` #` (space-then-hash). Such values are vanishingly rare; if
    # a power user needs them, they should drop a raw wpa_supplicant.conf
    # which we use verbatim.
    strip_inline_comment_and_ws() {
        printf '%s' "$1" | sed -E 's/[[:space:]]+#.*$//; s/^[[:space:]]+//; s/[[:space:]]+$//'
    }
    # Parse key=value lines, ignore comments and blanks. Strict matching
    # so a typo doesn't silently change behavior.
    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            ''|\#*) continue ;;
            SSID=*)    SSID=$(strip_inline_comment_and_ws "${line#SSID=}") ;;
            PSK=*)     PSK=$(strip_inline_comment_and_ws "${line#PSK=}") ;;
            COUNTRY=*) COUNTRY=$(strip_inline_comment_and_ws "${line#COUNTRY=}") ;;
            HIDDEN=*)  HIDDEN=$(strip_inline_comment_and_ws "${line#HIDDEN=}") ;;
        esac
    done < "$KV"

    if [ -z "$SSID" ]; then
        echo ">>> panicos-wifi-config: $KV has no SSID, skipping wifi"
        exit 0
    fi

    case "$SSID" in
        *'"'*|*\\*)
            echo ">>> panicos-wifi-config: SSID contains unsupported character (\" or \\), skipping wifi" >&2
            exit 1 ;;
    esac

    # Compute the hashed PSK before opening the output file so that a
    # wpa_passphrase failure (e.g. PSK < 8 chars) is caught before we create
    # a partial/empty conf.  HASHED is empty when PSK is absent (open net).
    HASHED=""
    if [ -n "$PSK" ]; then
        # wpa_passphrase emits a full network={} block; we only want the
        # hashed `psk=` line out of it.
        #
        # SECURITY NOTE — positional args vs. stdin pipe:
        # The cleaner form would be `printf '%s\n' "$PSK" | wpa_passphrase
        # "$SSID"` so the PSK never lands in argv (visible to /proc and
        # `ps`). wpa_supplicant 2.11 calls tcgetattr() on stdin and
        # rejects non-TTY input — every pipe / heredoc / fd / process-
        # substitution form errors with "tcgetattr: Inappropriate ioctl
        # for device". The on-device wpa_supplicant is the same 2.11,
        # so the stdin form is not viable at runtime either.
        #
        # We accept the positional-arg trade-off: the PSK is visible in
        # /proc/<pid>/cmdline only for the milliseconds wpa_passphrase
        # is alive, during single-user early boot before any non-root
        # process can read it. The PSK already lives in cleartext on
        # the unencrypted boot vfat that the user edited (the source-of-
        # truth file), so the practical exposure delta is negligible.
        # If wpa_supplicant ever drops the tcgetattr check, switch back
        # to the stdin form here.
        HASHED=$(wpa_passphrase "$SSID" "$PSK" \
            | awk '/^[[:space:]]*psk=/{sub(/^[[:space:]]+/,""); print; exit}')
        if [ -z "$HASHED" ]; then
            echo ">>> panicos-wifi-config: wpa_passphrase failed for SSID '$SSID' (PSK probably <8 chars), skipping wifi" >&2
            exit 1
        fi
    fi

    mkdir -p "$(dirname "$OUT")"
    {
        echo "# Generated by panicos-wifi-config from $KV"
        # ctrl_interface= and update_config= are deliberately omitted.
        # Buildroot's wpa_supplicant defaults to BR2_PACKAGE_WPA_SUPPLICANT_CTRL_IFACE=n,
        # which makes both options unrecognized and aborts conf parsing on the first
        # one. We don't use wpa_cli at runtime, so neither is needed.
        [ -n "$COUNTRY" ] && echo "country=$COUNTRY"
        echo "network={"
        echo "    ssid=\"$SSID\""
        [ "$HIDDEN" = "1" ] && echo "    scan_ssid=1"
        if [ -n "$PSK" ]; then
            echo "    $HASHED"
        else
            echo "    key_mgmt=NONE"
        fi
        echo "}"
    } > "$OUT"
    chmod 0600 "$OUT"
    echo ">>> panicos-wifi-config: rendered $KV → $OUT"
    exit 0
fi

# Case 3: no config.
echo ">>> panicos-wifi-config: no $RAW or $KV, skipping wifi"
exit 0
