[Autologin]
User=panicos
Session=wayfire

[General]
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot
DisplayStopCommand=/usr/bin/loginctl terminate-session $DISPLAY_ID
InputMethod=qtvirtualkeyboard

[Theme]
Current=breeze

[Wayland]
CompositorCommand=wayfire
