Syntax 2

UseCasePath.default {
    Version 2
    Directory "${CardId}"
    File "${CardId}.conf"
}

UseCasePath.conf-d {
    Version 2
    Directory "conf.d/${CardDriver}"
    File "${CardLongName}.conf"
}
