#!/usr/bin/env bash
# Compose a Buildroot defconfig from PanicOS fragments.
#
# A defconfig = concatenation of:
#   board/*/<device>/defconfig.fragment
#   flavors/<flavor>/defconfig.fragment              (optional)
#   soc/<soc>/<kernel>/**/defconfig.fragment         (all, recursive, when --kernel given)
#
# The soc tree may have subdirs (e.g. linux/, uboot/) each with their own
# defconfig.fragment; we concatenate every one we find.
#
# Empty fragments are tolerated. Missing device fragment is an error.

set -euo pipefail

usage() {
	cat >&2 <<EOF
Usage: $0 --device <name> --flavor <name> [--kernel <vendor|mainline>] [--soc <name>] --output <path>
EOF
	exit 2
}

DEVICE=""; FLAVOR=""; KERNEL=""; SOC=""; OUTPUT=""
while [ $# -gt 0 ]; do
	case "$1" in
		--device)  DEVICE="$2"; shift 2 ;;
		--flavor)  FLAVOR="$2"; shift 2 ;;
		--kernel)  KERNEL="$2"; shift 2 ;;
		--soc)     SOC="$2"; shift 2 ;;
		--output)  OUTPUT="$2"; shift 2 ;;
		*) usage ;;
	esac
done

[ -n "$DEVICE" ] && [ -n "$FLAVOR" ] && [ -n "$OUTPUT" ] || usage

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Locate the device fragment under any vendor dir.
DEVICE_FRAGMENT="$(find "$ROOT/board" -mindepth 3 -maxdepth 3 \
	-path "*/$DEVICE/defconfig.fragment" 2>/dev/null | head -1 || true)"
if [ -z "$DEVICE_FRAGMENT" ] || [ ! -f "$DEVICE_FRAGMENT" ]; then
	echo "error: no defconfig.fragment found for device '$DEVICE'" >&2
	exit 1
fi

FLAVOR_FRAGMENT="$ROOT/flavors/$FLAVOR/defconfig.fragment"

# Collect soc fragments (sorted, recursive) when --soc + --kernel are given.
SOC_FRAGMENTS=()
if [ -n "$KERNEL" ] && [ -n "$SOC" ]; then
	# Flavor-specific fragments (under soc/<soc>/<kernel>/)
	SOC_DIR="$ROOT/soc/$SOC/$KERNEL"
	if [ -d "$SOC_DIR" ]; then
		while IFS= read -r f; do
			SOC_FRAGMENTS+=("$f")
		done < <(find "$SOC_DIR" -name 'defconfig.fragment' -type f | LC_ALL=C sort)
	fi
	# Flavor-independent fragments (e.g. soc/<soc>/uboot/defconfig.fragment).
	# Walk soc/<soc>/<thing>/defconfig.fragment but exclude per-flavor subdirs.
	SOC_SHARED="$ROOT/soc/$SOC"
	if [ -d "$SOC_SHARED" ]; then
		while IFS= read -r f; do
			SOC_FRAGMENTS+=("$f")
		done < <(find "$SOC_SHARED" -mindepth 2 -maxdepth 3 -name 'defconfig.fragment' -type f \
		         -not -path "*/mainline/*" -not -path "*/vendor/*" \
		         | LC_ALL=C sort)
	fi
fi

mkdir -p "$(dirname "$OUTPUT")"
{
	echo "# Generated by gen-defconfig.sh on $(date -u +%FT%TZ)"
	echo "# device=$DEVICE flavor=$FLAVOR${KERNEL:+ kernel=$KERNEL}${SOC:+ soc=$SOC}"
	echo
	# Emit Kconfig symbols for our --kernel choice so Buildroot records
	# it (post-image.sh reads PANICOS_KERNEL_FLAVOR_NAME from .config).
	if [ -n "$KERNEL" ]; then
		echo "# Kernel flavor selection (from --kernel)"
		case "$KERNEL" in
			mainline) echo "PANICOS_KERNEL_FLAVOR_MAINLINE=y" ;;
			vendor)   echo "PANICOS_KERNEL_FLAVOR_VENDOR=y" ;;
			*) echo "# unknown KERNEL flavor: $KERNEL" >&2 ;;
		esac
		echo
	fi
	cat "$DEVICE_FRAGMENT"
	[ -f "$FLAVOR_FRAGMENT" ] && { echo; cat "$FLAVOR_FRAGMENT"; } || true
	if [ ${#SOC_FRAGMENTS[@]} -gt 0 ]; then
		for f in "${SOC_FRAGMENTS[@]}"; do
			[ -f "$f" ] || continue
			echo
			echo "# from: ${f#$ROOT/}"
			cat "$f"
		done
	fi
} > "$OUTPUT"
